---

hostname: R2

mgmt_address: 192.168.128.2

interfaces:
  - name: lo
    ip: 192.168.254.2/32
    type: loopback
  - name: eth2
    ip: '172.16.0.2/24'
    type: ethernet
  - name: eth3
    ip: '192.168.130.2/24'
    type: ethernet
  - name: eth4
    ip: '192.168.131.2/24'   
    type: ethernet 

RIP_config:
  networks:
    - '172.16.0.0/24'

