# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ansible/tower"
  config.vm.box_check_update = false

  config.vm.define "tower-vagrant"

  config.vm.hostname = "tower.rh.com"
  config.vm.network :forwarded_port, guest: 22, host: 2231, host_ip: "127.0.0.1", id: "ssh"
  config.vm.network :forwarded_port, guest: 443, host: 8443, host_ip: "127.0.0.1", id: "https"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.128.254", :adapter => 2, :netmask => "255.255.255.0"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/import_keys.pub"

  config.vm.provider "virtualbox" do |v, override|
    v.name = "tower-vagrant"
    v.memory = 1024
    v.cpus   = 2

    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.customize ["modifyvm", :id, "--nic2", "hostonly"]
    v.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet1"]                
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

$script = <<SCRIPT
#!/bin/bash
n=`atq | wc -l`; while (( $n != 0 )); do echo "waiting for Tower install to complete"; sleep 10; n=`atq | wc -l`; done
echo -n "Tower start complete"
echo -n "Installing SSH keys"
mkdir -p /root/.ssh
cp /home/vagrant/.ssh/import_keys.pub /root/.ssh/import_keys.pub
cd /root/.ssh/
cat import_keys.pub >> authorized_keys
sort authorized_keys | uniq > public_keys.pub
mv -f public_keys.pub authorized_keys
rm *.pub

mkdir -p /opt/venv
virtualenv -p /opt/rh/rh-python36/root/bin/python3 --system-site-packages /opt/venv/tower
/opt/venv/tower/bin/pip install graphviz ansible-tower-cli ansible 
echo -n "Finished"
/etc/profile.d/ansible-tower.sh

SCRIPT

  config .vm.provision "shell", inline: $script, privileged: true
end
