---
# tasks file

- name: retrieve configuraiton
  vyos_facts:
    gather_subset: config
  register: results

- debug: 
    var: results
    verbosity: 2

- name: 
  git:
    repo: "{{ config_git_repo }}"
    dest: "{{ local_git_conf_dir }}"
    accept_hostkey : yes
    force: yes
  run_once: true

- name: get current datetime as epoch
  local_action:
    module: command
    cmd: 'date +%s'
  register: date_as_epoch
  run_once: true  

- name: ensure direcory for router exists
  local_action:
      module: file
      path: "{{ local_git_conf_dir }}/{{ inventory_hostname }}"
      state: directory

- name: pull back config
  local_action:
    module: template
    src: config.j2
    dest: "{{ local_git_conf_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}-{{ date_as_epoch.stdout_lines.0 }}-config"

- name: check if existing GOLD config exists
  local_action:
    module: stat
    path: "{{ local_git_conf_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}-GOLD-config"
  register: stat_result

- name: install gold configuration
  local_action:
    module: template
    src: config.j2
    dest: "{{ local_git_conf_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}-GOLD-config"
  when: stat_result.stat.exists == False 

- name: commit
  local_action:
    module: shell 
    cmd: "git  -c 'user.name=Tower' -c 'user.email=node@tower.com' {{ item }}"  
    args:
      chdir: "{{ local_git_conf_dir }}/"
  loop: 
    - "add ."
    - "commit -m 'Router Config Updates - {{ date_as_epoch.stdout_lines.0 }}'"
    - "push"
  run_once: true

- name: linux diff compare
  local_action:
    module: shell
    cmd: "diff -c -w --strip-trailing-cr {{ inventory_hostname }}-GOLD-config {{ inventory_hostname }}-{{ date_as_epoch.stdout_lines.0 }}-config"
    args:
      chdir: "{{ local_git_conf_dir }}/{{ inventory_hostname }}/"
  register: diff_files
  ignore_errors: True

- debug: 
    var: diff_files.stdout_lines

- name: pull back config
  local_action:
    module: template
    src: email.j2
    dest: "/tmp/email-{{ inventory_hostname }}"

# Check if there is a difference in config and notify
- name: Sending an e-mail using the remote machine, not the Ansible controller node
  mail:
    host: localhost
    port: 25
    to: "{{ email_alert_address }}"
    subtype: html
    subject: Router Configuraiton Error - {{ inventory_hostname }}
    body: "{{ lookup('file', '/tmp/email-'~inventory_hostname) }}"
  when: diff_files.rc != 0
  
- name: remove email
  local_action:
    module: file
    path: "/tmp/email-{{ inventory_hostname }}"  
    state: absent
