---
# tasks file

- name: configure the pre-login banner
  vyos_banner:
    banner: pre-login
    text: "{{ new_login_banner }}"
    state: present

- name: remove the post-login banner
  vyos_banner:
    banner: post-login
    state: absent
