---

- name: generate network diagram
  local_action:
    module: script
    cmd: "dyn_gen_diagram.py --git_dir {{ local_git_conf_dir }}"

- name: Sending an e-mail using the remote machine, not the Ansible controller node
  mail:
    host: localhost
    port: 25
    to: "{{ email_alert_address }}"
    subtype: html
    subject: Network Diagram
    body: "Network Diagram"
    attach: "{{ lookup('file', local_git_conf_dir~'/network_diagram.pdf') }}"
