---

- name: get tower password
  shell:
    cmd: "cat /etc/profile.d/ansible-tower.sh | awk '/Password/ {print $4}'"
  register: results

- debug:
    var: results.stdout

- name: Create tower organization
  tower_organization:
    name: "{{ tower_org }}"
    description: "Red Hat Networking"
    state: present
    tower_host: "https://127.0.0.1:443"
    tower_password: "{{ results.stdout }}"
    tower_username: admin
    validate_certs: no

- name: Add tower project
  tower_project:
    name: "ansible-networking"
    description: "ansible-networking"
    organization: "{{ tower_org }}"
    scm_type: git
    scm_url: https://github.com/snowjet/ansible-network-example.git
    scm_branch: master
    scm_update_on_launch: true
    state: present
    tower_host: "https://127.0.0.1:443"
    tower_password: "{{ results.stdout }}"
    tower_username: admin
    validate_certs: no

- name: Add tower inventory
  tower_inventory:
    name: "Routers"
    description: "Routers to Configure"
    organization: "{{ tower_org }}"
    state: present
    tower_host: "https://127.0.0.1:443"
    tower_password: "{{ results.stdout }}"
    tower_username: admin
    validate_certs: no

- name: Add tower Router inventory source
  tower_inventory_source:
    name: Router Inventory source
    description: Router Inventory source
    inventory: Routers
    source: scm
    source_path: inventory
    source_project: ansible-networking
    update_on_launch: true
    overwrite: true
    state: present
    tower_host: "https://127.0.0.1:443"
    tower_password: "{{ results.stdout }}"
    tower_username: admin
    validate_certs: no

- name: Create a valid vyos-ssh credential 
  tower_credential:
    name: vyos-ssh
    organization:  "{{ tower_org }}"
    state: present
    kind: net
    username: vyos
    password: vyos
    tower_host: "https://127.0.0.1:443"
    tower_password: "{{ results.stdout }}"
    tower_username: admin
    validate_certs: no

- name: Create Template 01 Global Change
  tower_job_template:
    name: "01 - Global Change"
    job_type: "run"
    inventory: "Routers"
    project: "ansible-networking"
    playbook: "global-change.yml"
    credential: "vyos-ssh"
    state: "present"
    tower_host: "https://127.0.0.1:443"
    tower_password: "{{ results.stdout }}"
    tower_username: admin
    validate_certs: no